# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/maks/myfolder/BSUIR/PBZ/lab2/solution/pds-calculator/view/ui/AddEditCompanyTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCompanyWidget(object):
    def __init__(self, form) -> None:
        self.setupUi(AddEditCompanyWidget=form)
    
    def setupUi(self, AddEditCompanyWidget):
        AddEditCompanyWidget.setObjectName("AddEditCompanyWidget")
        AddEditCompanyWidget.resize(600, 800)
        self.CompanyGroupBox = QtWidgets.QGroupBox(AddEditCompanyWidget)
        self.CompanyGroupBox.setGeometry(QtCore.QRect(20, 10, 341, 131))
        self.CompanyGroupBox.setObjectName("CompanyGroupBox")
        self.CompanyNameLineEdit = QtWidgets.QLineEdit(self.CompanyGroupBox)
        self.CompanyNameLineEdit.setGeometry(QtCore.QRect(60, 30, 113, 25))
        self.CompanyNameLineEdit.setObjectName("CompanyNameLineEdit")
        self.CompanyNameLabel = QtWidgets.QLabel(self.CompanyGroupBox)
        self.CompanyNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.CompanyNameLabel.setObjectName("CompanyNameLabel")
        self.CompanyWaterUseTypeLabel_2 = QtWidgets.QLabel(self.CompanyGroupBox)
        self.CompanyWaterUseTypeLabel_2.setGeometry(QtCore.QRect(10, 70, 121, 17))
        self.CompanyWaterUseTypeLabel_2.setObjectName("CompanyWaterUseTypeLabel_2")
        self.WaterUseTypeComboBox = QtWidgets.QComboBox(self.CompanyGroupBox)
        self.WaterUseTypeComboBox.setGeometry(QtCore.QRect(130, 70, 86, 25))
        self.WaterUseTypeComboBox.setObjectName("WaterUseTypeComboBox")
        self.CompanyConfirmPushButton = QtWidgets.QPushButton(AddEditCompanyWidget)
        self.CompanyConfirmPushButton.setGeometry(QtCore.QRect(130, 150, 89, 25))
        self.CompanyConfirmPushButton.setObjectName("CompanyConfirmPushButton")
        self.AddEditCompanyBackPushButton = QtWidgets.QPushButton(AddEditCompanyWidget)
        self.AddEditCompanyBackPushButton.setGeometry(QtCore.QRect(20, 760, 89, 25))
        self.AddEditCompanyBackPushButton.setObjectName("AddEditCompanyBackPushButton")

        self.retranslateUi(AddEditCompanyWidget)
        QtCore.QMetaObject.connectSlotsByName(AddEditCompanyWidget)

    def retranslateUi(self, AddEditCompanyWidget):
        _translate = QtCore.QCoreApplication.translate
        AddEditCompanyWidget.setWindowTitle(_translate("AddEditCompanyWidget", "Form"))
        self.CompanyGroupBox.setTitle(_translate("AddEditCompanyWidget", "Company Add/Edit"))
        self.CompanyNameLabel.setText(_translate("AddEditCompanyWidget", "Name:"))
        self.CompanyWaterUseTypeLabel_2.setText(_translate("AddEditCompanyWidget", "Water Use Type:"))
        self.CompanyConfirmPushButton.setText(_translate("AddEditCompanyWidget", "Confirm"))
        self.AddEditCompanyBackPushButton.setText(_translate("AddEditCompanyWidget", "Back"))
