# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/maks/myfolder/BSUIR/PBZ/lab2/solution/pds-calculator/view/ui/AddEditCanalizationTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Add
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCanalizationWidget(object):
    def __init__(self, form) -> None:
        self.setupUi(AddEditCanalizationWidget=form)
    
    def setupUi(self, AddEditCanalizationWidget):
        AddEditCanalizationWidget.setObjectName("AddEditCanalizationWidget")
        AddEditCanalizationWidget.resize(600, 800)
        self.CanalizationGroupBox = QtWidgets.QGroupBox(AddEditCanalizationWidget)
        self.CanalizationGroupBox.setGeometry(QtCore.QRect(20, 10, 341, 371))
        self.CanalizationGroupBox.setObjectName("CanalizationGroupBox")
        self.CanalizationNameLineEdit = QtWidgets.QLineEdit(self.CanalizationGroupBox)
        self.CanalizationNameLineEdit.setGeometry(QtCore.QRect(60, 30, 113, 25))
        self.CanalizationNameLineEdit.setObjectName("CanalizationNameLineEdit")
        self.CanalizationNameLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.CanalizationNameLabel.setObjectName("CanalizationNameLabel")
        self.CanalizationCompanyLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationCompanyLabel.setGeometry(QtCore.QRect(10, 70, 71, 17))
        self.CanalizationCompanyLabel.setObjectName("CanalizationCompanyLabel")
        self.CanalizationCompanyComboBox = QtWidgets.QComboBox(self.CanalizationGroupBox)
        self.CanalizationCompanyComboBox.setGeometry(QtCore.QRect(90, 70, 111, 25))
        self.CanalizationCompanyComboBox.setObjectName("CanalizationCompanyComboBox")
        self.CanalizationControlGateLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationControlGateLabel.setGeometry(QtCore.QRect(10, 110, 101, 17))
        self.CanalizationControlGateLabel.setObjectName("CanalizationControlGateLabel")
        self.CanalizationControlGateComboBox = QtWidgets.QComboBox(self.CanalizationGroupBox)
        self.CanalizationControlGateComboBox.setGeometry(QtCore.QRect(110, 110, 101, 25))
        self.CanalizationControlGateComboBox.setObjectName("CanalizationControlGateComboBox")
        self.CanalizationHeightLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationHeightLabel.setGeometry(QtCore.QRect(10, 240, 67, 17))
        self.CanalizationHeightLabel.setObjectName("CanalizationHeightLabel")
        self.CanalizationHoleDiameterLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationHoleDiameterLabel.setGeometry(QtCore.QRect(10, 180, 111, 17))
        self.CanalizationHoleDiameterLabel.setObjectName("CanalizationHoleDiameterLabel")
        self.CanalizationControlGateDistanceLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationControlGateDistanceLabel.setGeometry(QtCore.QRect(10, 210, 161, 17))
        self.CanalizationControlGateDistanceLabel.setObjectName("CanalizationControlGateDistanceLabel")
        self.CanalizationWaterWasteLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationWaterWasteLabel.setGeometry(QtCore.QRect(10, 330, 101, 17))
        self.CanalizationWaterWasteLabel.setObjectName("CanalizationWaterWasteLabel")
        self.CanalizationAngleLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationAngleLabel.setGeometry(QtCore.QRect(10, 270, 67, 17))
        self.CanalizationAngleLabel.setObjectName("CanalizationAngleLabel")
        self.CanalizationMinWaterSpeedLabel = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationMinWaterSpeedLabel.setGeometry(QtCore.QRect(10, 300, 121, 17))
        self.CanalizationMinWaterSpeedLabel.setObjectName("CanalizationMinWaterSpeedLabel")
        self.CanalizationHoleDiameterLabel_2 = QtWidgets.QLabel(self.CanalizationGroupBox)
        self.CanalizationHoleDiameterLabel_2.setGeometry(QtCore.QRect(10, 150, 111, 17))
        self.CanalizationHoleDiameterLabel_2.setObjectName("CanalizationHoleDiameterLabel_2")
        self.CanalizationHoleDiameterDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.CanalizationGroupBox)
        self.CanalizationHoleDiameterDoubleSpinBox.setGeometry(QtCore.QRect(120, 150, 65, 26))
        self.CanalizationHoleDiameterDoubleSpinBox.setObjectName("CanalizationHoleDiameterDoubleSpinBox")
        self.CanalizationShoreDIstanceSpinBox = QtWidgets.QSpinBox(self.CanalizationGroupBox)
        self.CanalizationShoreDIstanceSpinBox.setGeometry(QtCore.QRect(120, 180, 44, 26))
        self.CanalizationShoreDIstanceSpinBox.setObjectName("CanalizationShoreDIstanceSpinBox")
        self.CanalizationControlGateDistanceSpinBox = QtWidgets.QSpinBox(self.CanalizationGroupBox)
        self.CanalizationControlGateDistanceSpinBox.setGeometry(QtCore.QRect(170, 210, 44, 26))
        self.CanalizationControlGateDistanceSpinBox.setObjectName("CanalizationControlGateDistanceSpinBox")
        self.CanalizationHeightDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.CanalizationGroupBox)
        self.CanalizationHeightDoubleSpinBox.setGeometry(QtCore.QRect(70, 240, 65, 26))
        self.CanalizationHeightDoubleSpinBox.setObjectName("CanalizationHeightDoubleSpinBox")
        self.CanalizationAngleSpinBox = QtWidgets.QSpinBox(self.CanalizationGroupBox)
        self.CanalizationAngleSpinBox.setGeometry(QtCore.QRect(60, 270, 44, 26))
        self.CanalizationAngleSpinBox.setObjectName("CanalizationAngleSpinBox")
        self.CanalizationMinWaterSpeedDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.CanalizationGroupBox)
        self.CanalizationMinWaterSpeedDoubleSpinBox.setGeometry(QtCore.QRect(140, 290, 65, 26))
        self.CanalizationMinWaterSpeedDoubleSpinBox.setObjectName("CanalizationMinWaterSpeedDoubleSpinBox")
        self.CanalizationWaterWasteDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.CanalizationGroupBox)
        self.CanalizationWaterWasteDoubleSpinBox.setGeometry(QtCore.QRect(110, 330, 65, 26))
        self.CanalizationWaterWasteDoubleSpinBox.setObjectName("CanalizationWaterWasteDoubleSpinBox")
        self.CanalizationConfirmPushButton = QtWidgets.QPushButton(AddEditCanalizationWidget)
        self.CanalizationConfirmPushButton.setGeometry(QtCore.QRect(120, 390, 89, 25))
        self.CanalizationConfirmPushButton.setObjectName("CanalizationConfirmPushButton")
        self.ADdEditcanalizationBackPushButton = QtWidgets.QPushButton(AddEditCanalizationWidget)
        self.ADdEditcanalizationBackPushButton.setGeometry(QtCore.QRect(10, 760, 89, 25))
        self.ADdEditcanalizationBackPushButton.setObjectName("ADdEditcanalizationBackPushButton")

        self.retranslateUi(AddEditCanalizationWidget)
        QtCore.QMetaObject.connectSlotsByName(AddEditCanalizationWidget)

    def retranslateUi(self, AddEditCanalizationWidget):
        _translate = QtCore.QCoreApplication.translate
        AddEditCanalizationWidget.setWindowTitle(_translate("AddEditCanalizationWidget", "Form"))
        self.CanalizationGroupBox.setTitle(_translate("AddEditCanalizationWidget", "Canalization Add/Edit"))
        self.CanalizationNameLabel.setText(_translate("AddEditCanalizationWidget", "Name:"))
        self.CanalizationCompanyLabel.setText(_translate("AddEditCanalizationWidget", "Company:"))
        self.CanalizationControlGateLabel.setText(_translate("AddEditCanalizationWidget", "Control Gate:"))
        self.CanalizationHeightLabel.setText(_translate("AddEditCanalizationWidget", "Height:"))
        self.CanalizationHoleDiameterLabel.setText(_translate("AddEditCanalizationWidget", "Shore Distance:"))
        self.CanalizationControlGateDistanceLabel.setText(_translate("AddEditCanalizationWidget", "Control Gate Distance:"))
        self.CanalizationWaterWasteLabel.setText(_translate("AddEditCanalizationWidget", "Water Waste:"))
        self.CanalizationAngleLabel.setText(_translate("AddEditCanalizationWidget", "Angle:"))
        self.CanalizationMinWaterSpeedLabel.setText(_translate("AddEditCanalizationWidget", "Min WaterSpeed:"))
        self.CanalizationHoleDiameterLabel_2.setText(_translate("AddEditCanalizationWidget", "hole Diameter:"))
        self.CanalizationConfirmPushButton.setText(_translate("AddEditCanalizationWidget", "Confirm"))
        self.ADdEditcanalizationBackPushButton.setText(_translate("AddEditCanalizationWidget", "Back"))
