# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/maks/myfolder/BSUIR/PBZ/lab2/solution/pds-calculator/view/ui/AddDateTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Add
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDateWidget(object):
    def __init__(self, form) -> None:
        self.setupUi(AddDateWidget=form)
    
    def setupUi(self, AddDateWidget):
        AddDateWidget.setObjectName("AddDateWidget")
        AddDateWidget.resize(600, 800)
        self.DateGroupBox = QtWidgets.QGroupBox(AddDateWidget)
        self.DateGroupBox.setGeometry(QtCore.QRect(20, 10, 341, 221))
        self.DateGroupBox.setObjectName("DateGroupBox")
        self.DateLabel = QtWidgets.QLabel(self.DateGroupBox)
        self.DateLabel.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.DateLabel.setObjectName("DateLabel")
        self.DatePollutantLabel = QtWidgets.QLabel(self.DateGroupBox)
        self.DatePollutantLabel.setGeometry(QtCore.QRect(10, 70, 71, 17))
        self.DatePollutantLabel.setObjectName("DatePollutantLabel")
        self.DatePollutantComboBox = QtWidgets.QComboBox(self.DateGroupBox)
        self.DatePollutantComboBox.setGeometry(QtCore.QRect(90, 70, 111, 25))
        self.DatePollutantComboBox.setObjectName("DatePollutantComboBox")
        self.ControlGateBCLabel = QtWidgets.QLabel(self.DateGroupBox)
        self.ControlGateBCLabel.setGeometry(QtCore.QRect(10, 110, 121, 17))
        self.ControlGateBCLabel.setObjectName("ControlGateBCLabel")
        self.DatePDKLabel = QtWidgets.QLabel(self.DateGroupBox)
        self.DatePDKLabel.setGeometry(QtCore.QRect(10, 180, 41, 17))
        self.DatePDKLabel.setObjectName("DatePDKLabel")
        self.CanalizationBCLabel = QtWidgets.QLabel(self.DateGroupBox)
        self.CanalizationBCLabel.setGeometry(QtCore.QRect(10, 150, 111, 17))
        self.CanalizationBCLabel.setObjectName("CanalizationBCLabel")
        self.DateControlGateBCSpinBox = QtWidgets.QSpinBox(self.DateGroupBox)
        self.DateControlGateBCSpinBox.setGeometry(QtCore.QRect(130, 110, 44, 26))
        self.DateControlGateBCSpinBox.setObjectName("DateControlGateBCSpinBox")
        self.DateCanalizationBCSpinBox = QtWidgets.QSpinBox(self.DateGroupBox)
        self.DateCanalizationBCSpinBox.setGeometry(QtCore.QRect(130, 150, 44, 26))
        self.DateCanalizationBCSpinBox.setObjectName("DateCanalizationBCSpinBox")
        self.DateEdit = QtWidgets.QDateEdit(self.DateGroupBox)
        self.DateEdit.setGeometry(QtCore.QRect(70, 30, 110, 26))
        self.DateEdit.setObjectName("DateEdit")
        self.DatePDKSpinBox = QtWidgets.QSpinBox(self.DateGroupBox)
        self.DatePDKSpinBox.setGeometry(QtCore.QRect(50, 180, 44, 26))
        self.DatePDKSpinBox.setObjectName("DatePDKSpinBox")
        self.DateConfirmPushButton = QtWidgets.QPushButton(AddDateWidget)
        self.DateConfirmPushButton.setGeometry(QtCore.QRect(140, 240, 89, 25))
        self.DateConfirmPushButton.setObjectName("DateConfirmPushButton")
        self.AddDateBackPushButton = QtWidgets.QPushButton(AddDateWidget)
        self.AddDateBackPushButton.setGeometry(QtCore.QRect(10, 760, 89, 25))
        self.AddDateBackPushButton.setObjectName("AddDateBackPushButton")

        self.retranslateUi(AddDateWidget)
        QtCore.QMetaObject.connectSlotsByName(AddDateWidget)

    def retranslateUi(self, AddDateWidget):
        _translate = QtCore.QCoreApplication.translate
        AddDateWidget.setWindowTitle(_translate("AddDateWidget", "Form"))
        self.DateGroupBox.setTitle(_translate("AddDateWidget", "Date Add"))
        self.DateLabel.setText(_translate("AddDateWidget", "Date:"))
        self.DatePollutantLabel.setText(_translate("AddDateWidget", "Pollutant:"))
        self.ControlGateBCLabel.setText(_translate("AddDateWidget", "Control Gate BC:"))
        self.DatePDKLabel.setText(_translate("AddDateWidget", "PDK:"))
        self.CanalizationBCLabel.setText(_translate("AddDateWidget", "Canalization BC:"))
        self.DateConfirmPushButton.setText(_translate("AddDateWidget", "Confirm"))
        self.AddDateBackPushButton.setText(_translate("AddDateWidget", "Back"))
