# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/maks/myfolder/BSUIR/PBZ/lab2/solution/pds-calculator/view/ui/AddPollutantTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPollutantWidget(object):
    def __init__(self, form) -> None:
        self.setupUi(AddPollutantWidget=form)
    
    def setupUi(self, AddPollutantWidget):
        AddPollutantWidget.setObjectName("AddPollutantWidget")
        AddPollutantWidget.resize(600, 800)
        self.PollutantGroupBox = QtWidgets.QGroupBox(AddPollutantWidget)
        self.PollutantGroupBox.setGeometry(QtCore.QRect(20, 10, 341, 251))
        self.PollutantGroupBox.setObjectName("PollutantGroupBox")
        self.PollutantNameLineEdit = QtWidgets.QLineEdit(self.PollutantGroupBox)
        self.PollutantNameLineEdit.setGeometry(QtCore.QRect(60, 30, 113, 25))
        self.PollutantNameLineEdit.setObjectName("PollutantNameLineEdit")
        self.PollutantNameLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantNameLabel.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.PollutantNameLabel.setObjectName("PollutantNameLabel")
        self.PollutantCanalizationLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantCanalizationLabel.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.PollutantCanalizationLabel.setObjectName("PollutantCanalizationLabel")
        self.PollutantCanalizationComboBox = QtWidgets.QComboBox(self.PollutantGroupBox)
        self.PollutantCanalizationComboBox.setGeometry(QtCore.QRect(120, 70, 111, 25))
        self.PollutantCanalizationComboBox.setObjectName("PollutantCanalizationComboBox")
        self.PollutantGroupLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantGroupLabel.setGeometry(QtCore.QRect(10, 110, 51, 17))
        self.PollutantGroupLabel.setObjectName("PollutantGroupLabel")
        self.PollutantGroupComboBox = QtWidgets.QComboBox(self.PollutantGroupBox)
        self.PollutantGroupComboBox.setGeometry(QtCore.QRect(70, 110, 101, 25))
        self.PollutantGroupComboBox.setObjectName("PollutantGroupComboBox")
        self.PollutantKNKLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantKNKLabel.setGeometry(QtCore.QRect(10, 180, 41, 17))
        self.PollutantKNKLabel.setObjectName("PollutantKNKLabel")
        self.PollutantLFVLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantLFVLabel.setGeometry(QtCore.QRect(10, 210, 41, 17))
        self.PollutantLFVLabel.setObjectName("PollutantLFVLabel")
        self.PollutantDangerClassLabel = QtWidgets.QLabel(self.PollutantGroupBox)
        self.PollutantDangerClassLabel.setGeometry(QtCore.QRect(10, 150, 91, 17))
        self.PollutantDangerClassLabel.setObjectName("PollutantDangerClassLabel")
        self.PollutantKNKSpinBox = QtWidgets.QSpinBox(self.PollutantGroupBox)
        self.PollutantKNKSpinBox.setGeometry(QtCore.QRect(60, 180, 44, 26))
        self.PollutantKNKSpinBox.setObjectName("PollutantKNKSpinBox")
        self.PollutantLFVSpinBox = QtWidgets.QSpinBox(self.PollutantGroupBox)
        self.PollutantLFVSpinBox.setGeometry(QtCore.QRect(60, 210, 44, 26))
        self.PollutantLFVSpinBox.setObjectName("PollutantLFVSpinBox")
        self.PollutantDangerClassComboBox = QtWidgets.QComboBox(self.PollutantGroupBox)
        self.PollutantDangerClassComboBox.setGeometry(QtCore.QRect(110, 150, 101, 25))
        self.PollutantDangerClassComboBox.setObjectName("PollutantDangerClassComboBox")
        self.PollutantConfirmPushButton = QtWidgets.QPushButton(AddPollutantWidget)
        self.PollutantConfirmPushButton.setGeometry(QtCore.QRect(130, 270, 89, 25))
        self.PollutantConfirmPushButton.setObjectName("PollutantConfirmPushButton")
        self.AddPollutantBackPushButton = QtWidgets.QPushButton(AddPollutantWidget)
        self.AddPollutantBackPushButton.setGeometry(QtCore.QRect(10, 760, 89, 25))
        self.AddPollutantBackPushButton.setObjectName("AddPollutantBackPushButton")

        self.retranslateUi(AddPollutantWidget)
        QtCore.QMetaObject.connectSlotsByName(AddPollutantWidget)

    def retranslateUi(self, AddPollutantWidget):
        _translate = QtCore.QCoreApplication.translate
        AddPollutantWidget.setWindowTitle(_translate("AddPollutantWidget", "Form"))
        self.PollutantGroupBox.setTitle(_translate("AddPollutantWidget", "Pollutant Add"))
        self.PollutantNameLabel.setText(_translate("AddPollutantWidget", "Name:"))
        self.PollutantCanalizationLabel.setText(_translate("AddPollutantWidget", "Canalization:"))
        self.PollutantGroupLabel.setText(_translate("AddPollutantWidget", "Group:"))
        self.PollutantKNKLabel.setText(_translate("AddPollutantWidget", "KNK:"))
        self.PollutantLFVLabel.setText(_translate("AddPollutantWidget", "LFV:"))
        self.PollutantDangerClassLabel.setText(_translate("AddPollutantWidget", "Danger Class:"))
        self.PollutantConfirmPushButton.setText(_translate("AddPollutantWidget", "Confirm"))
        self.AddPollutantBackPushButton.setText(_translate("AddPollutantWidget", "Back"))
