# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/maks/myfolder/BSUIR/PBZ/lab2/solution/pds-calculator/view/ui/HomeTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWidget(object):
    def __init__(self, form) -> None:
        self.setupUi(HomeWidget=form)
    
    def setupUi(self, HomeWidget):
        HomeWidget.setObjectName("HomeWidget")
        HomeWidget.resize(600, 800)
        self.CompaniesPushButton = QtWidgets.QPushButton(HomeWidget)
        self.CompaniesPushButton.setGeometry(QtCore.QRect(10, 10, 89, 25))
        self.CompaniesPushButton.setObjectName("CompaniesPushButton")
        self.CanalizationsPushButton = QtWidgets.QPushButton(HomeWidget)
        self.CanalizationsPushButton.setGeometry(QtCore.QRect(110, 10, 101, 25))
        self.CanalizationsPushButton.setObjectName("CanalizationsPushButton")
        self.PollutantsPushButton = QtWidgets.QPushButton(HomeWidget)
        self.PollutantsPushButton.setGeometry(QtCore.QRect(220, 10, 89, 25))
        self.PollutantsPushButton.setObjectName("PollutantsPushButton")
        self.ExitHomePushButton = QtWidgets.QPushButton(HomeWidget)
        self.ExitHomePushButton.setGeometry(QtCore.QRect(20, 750, 89, 25))
        self.ExitHomePushButton.setObjectName("ExitHomePushButton")

        self.retranslateUi(HomeWidget)
        QtCore.QMetaObject.connectSlotsByName(HomeWidget)

    def retranslateUi(self, HomeWidget):
        _translate = QtCore.QCoreApplication.translate
        HomeWidget.setWindowTitle(_translate("HomeWidget", "Form"))
        self.CompaniesPushButton.setText(_translate("HomeWidget", "Companies"))
        self.CanalizationsPushButton.setText(_translate("HomeWidget", "Canalizations"))
        self.PollutantsPushButton.setText(_translate("HomeWidget", "Pollutants"))
        self.ExitHomePushButton.setText(_translate("HomeWidget", "Exit"))
